<?xml version="1.0"?>
<!--
  Camera Sensor Definition
  Module Owner: Abel (Modeling) / Netsanet (Obstacle Avoidance)
  
  RGB Camera for visual perception and object detection.
  Essential for pedestrian and vehicle detection in Addis Ababa traffic.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Camera Parameters -->
  <xacro:property name="camera_size" value="0.03"/>
  <xacro:property name="camera_mass" value="0.1"/>

  <xacro:macro name="camera_sensor" params="parent *origin">
    
    <!-- Camera Link -->
    <link name="camera_link">
      <visual>
        <geometry>
          <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <geometry>
          <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="${camera_mass}"/>
        <inertia ixx="${(camera_mass/12)*(camera_size*camera_size*5)}" ixy="0" ixz="0"
                 iyy="${(camera_mass/12)*(camera_size*camera_size*2)}" iyz="0"
                 izz="${(camera_mass/12)*(camera_size*camera_size*5)}"/>
      </inertial>
    </link>

    <!-- Camera Optical Frame (Z forward, X right, Y down) -->
    <link name="camera_optical_link"/>

    <joint name="camera_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="camera_link"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <joint name="camera_optical_joint" type="fixed">
      <parent link="camera_link"/>
      <child link="camera_optical_link"/>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <!-- Gazebo Camera Plugin -->
    <gazebo reference="camera_link">
      <sensor name="camera" type="camera">
        <always_on>true</always_on>
        <visualize>true</visualize>
        <update_rate>30.0</update_rate>
        <camera>
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>100</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <ros>
            <namespace>/</namespace>
            <remapping>~/image_raw:=camera/image_raw</remapping>
            <remapping>~/camera_info:=camera/camera_info</remapping>
          </ros>
          <camera_name>camera</camera_name>
          <frame_name>camera_optical_link</frame_name>
          <hack_baseline>0.07</hack_baseline>
        </plugin>
      </sensor>
      <material>Gazebo/Black</material>
    </gazebo>

  </xacro:macro>

</robot>
